title: Settings
fields:
  -
    handle: has_pattern
    field:
      type: toggle
      display: 'Background Pattern'
      localizable: false
  -
    handle: hide_header
    field:
      type: toggle
      display: 'Hide Header?'
      instructions: 'Aktuelle Seite ohne Header anzeigen.'
      localizable: false
  -
    handle: page_class
    field:
      options:
        privacy: Privacy
      type: select
      display: 'Page class'
      localizable: false
  -
    handle: template
    field:
      type: template
      display: Template
      localizable: false
  -
    handle: layout
    field:
      type: template
      display: Layout
      localizable: false
  -
    handle: debug
    field:
      type: toggle
      display: Debug
      localizable: false
