title: Aktuell
updated_by: c2f8321e-be41-4d83-b9ee-8136dba46b39
updated_at: 1715069841
blueprint: category
localizations:
  fr:
    title: Actualités
    slug: actualites
    updated_by: c2f8321e-be41-4d83-b9ee-8136dba46b39
    updated_at: 1715931932
  it:
    title: Attualità
    slug: attualita
    updated_by: c2f8321e-be41-4d83-b9ee-8136dba46b39
    updated_at: 1715932577
