title: Fachthemen
updated_by: c2f8321e-be41-4d83-b9ee-8136dba46b39
updated_at: 1715697780
blueprint: category
localizations:
  fr:
    title: Thématiques
    slug: fachthemen
    updated_by: c2f8321e-be41-4d83-b9ee-8136dba46b39
    updated_at: 1715930688
  it:
    title: 'Temi specialistici'
    slug: fachthemen
    updated_by: c2f8321e-be41-4d83-b9ee-8136dba46b39
    updated_at: 1715930690
