title: Verband
updated_by: c2f8321e-be41-4d83-b9ee-8136dba46b39
updated_at: 1715697848
blueprint: category
localizations:
  fr:
    title: Association
    slug: verband
    updated_by: c2f8321e-be41-4d83-b9ee-8136dba46b39
    updated_at: 1715930713
  it:
    title: Associazione
    slug: verband
    updated_by: c2f8321e-be41-4d83-b9ee-8136dba46b39
    updated_at: 1715930716
