title: Verband
updated_by: c2f8321e-be41-4d83-b9ee-8136dba46b39
updated_at: 1715697848
blueprint: category
localizations:
  fr:
    title: Association
    slug: association
    updated_by: c2f8321e-be41-4d83-b9ee-8136dba46b39
    updated_at: 1715697867
  it:
    title: Associazione
    slug: associazione
    updated_by: c2f8321e-be41-4d83-b9ee-8136dba46b39
    updated_at: 1715697878
